[package]
name = "ffcli"
version = "0.1.0"
authors = ["DarkSky"]
edition = "2018"
description = "A ffmpeg cli args builder"
include = ["src/**/*", "Cargo.toml"]
license = "AGPL-3.0-or-later"

[dependencies]
failure = "0.1.5"
log = "0.4.7"
